const genreOptions = [
  "Bollywood",
  "English/Western",
  "Hindi",
  "Punjabi",
  "Ghazal",
  "Sufi",
  "Qawwali",
  "Rock",
  "Pop",
  "Jazz",
  "Electronic",
  "Bollywood Retro/Old",
  "Orchestra (Bollywood Retro)",
  "Symphony",
  "Karaoke",
  "English Retro",
  "Indie",
  "English Blues",
  "Blues",
  "Classical",
  "Punjabi Folk",
  "Semi Classical",
  "Metal",
  "Soft Rock",
  "Alternative Rock",
  "Rajasthani Folk",
  "Bhojpuri",
  "Bengali",
  "Assame",
  "Dandiya/Garba",
  "Marathi",
  "Punjabi Tappe",
  "Bhangara",
  "Ravindra Sangeet",
  "Odia",
  "Devotional/Bhajan",
  "Hip Hop",
  "Tamil",
  "Malayalam",
  "Telugu",
  "Gujarati",
  "Sindhi",
  "Carnatic Music",
  "Maithili",
  "R&B",
  "Country",
  "Reggage",
  "Punk",
  "Funk",
  "Rap",
];

export default genreOptions;
